# Configs for pwills.com

title: Phylogenetic Comparative Methods at UH
name: Rosana Zenil-Ferguson
email: roszenil@hawaii.edu
url: "roszenil.github.io"
repository: "roszenil/roszenil.github.io"

include:
  - _pages
  - assets
  - index.html

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: contrast
  
# settings for author profile
author:
  name   : "Rosana Zenil-Ferguson"
  avatar : "/assets/images/mypicsmall.png"
  bio    : "Assistant Professor. University of Hawai'i"
  location: "Honolulu, HI"
  github : rozenil
  email  : roszenil@hawaii.edu


# pagination for blog page
#paginate: 2 # number of posts to show
#paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
