# Configs for pwills.com

title: Phylogenetic Comparative Methods at UH
name: Rosana Zenil-Ferguson
email: roszenil@hawaii.edu
url: "roszenil.github.io"
repository: "roszenil/roszenil.github.io"

include:
  - _pages
  - assets
  - index.html

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
  
# settings for author profile
author:
  name   : "Rosana Zenil-Ferguson"
  avatar : "/assets/images/ls2.jpg"
  bio    : "Assistant Professor. University of Hawai'i"
  email  : roszenil@hawaii.edu
  links:
    - label: roszenil.github.io
      icon: "fas fa-fw fa-link"
      url: https://roszenil.github.io
    - label: roszenil
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/roszenil
    - label: roszenil
      icon: "fab fa-fw fa-github"
      url: https://github.com/roszenil

footer:
  links:
    - label: roszenil
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/roszenil
    - label: Github
      icon: "fab fa-fw fa-github"
      url: https://github.com/roszenil

# pagination for blog page
#paginate: 3 # number of posts to show
#paginate_path: /page:num/

# default YAML front matter
collections:
      teaching:
      output: true
      permalink: /teaching/
      
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: false
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
  # teaching
  - scope:
      path: ""
      layout: single
      type: teaching
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "teaching"

    
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/